spring.application.name=backendBankuNiebieskiego
server.port=8081
# Zmieniamy port na 8081, ?eby nie gryz? si? ze sklepem (8080) i w przysz?o?ci z Blikiem (8082) itp.

# Konfiguracja MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/blue_bank?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
# (Wpisz swoje has?o do MySQL, domy?lnie w XAMPP jest puste)

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

blik.url=http://192.168.0.173:8082/api/blik